using System.Text;

namespace AjaxService.Gen.Models.Typescript;

public sealed class ModelsTs : TsFileBase
{
    private ModelsTs(string path) : base(path) { }
    public static ModelsTs From(string path)
    {
        const string defaultContent =
"""
//This File is autogenerated, DO NOT touch this file!
export type OneOf<Error, Success> = Left<Error> | Right<Success>;
export class Left<T> {
    readonly Error: T;

    private constructor(error: T) {
        this.Error = error;
    }

    IsLeft(): this is Left<T> {
        return true;
    }

    IsRight(): this is Right<never> {
        return false;
    }

    static Create = <E>(error: E) => new Left(error);
}

export class Right<T> {
    readonly Value: T;

    private constructor(value: T) {
        this.Value = value;
    }

    IsLeft(): this is Left<never> {
        return false;
    }

    IsRight(): this is Right<T> {
        return true;
    }

    static Create = <S>(value: S) => new Right(value);
}

""";
        File.WriteAllText(path, defaultContent, Encoding.UTF8);
        return new(path);
    }
}